### ISSUE TITLE
Files are empty

### ISSUE THREAD

**Issue by matthewlucock** [lyneca/zr-git-session#1]
I tried to run the tests but their weren't any tests to run.

Microsoft Windows [Version 10.0.15063]
npm 5.4.1
node 8.4.0
python 3.6.1
go version go1.8.3 windows/amd64

**Comment by lyneca** [comment]
This repository does not have any tests

**Comment by Booligoosh** [comment]
👎

**Comment by matthewlucock** [comment]
+1
